DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS xray_results;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE xray_results(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  xray_name TEXT UNIQUE NOT NULL,
  result INT NOT NULL
)